# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  publish-documentation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Install doxygen
      run: |
        sudo apt-get update
        sudo apt-get -y install doxygen
    - name: Run doxygen
      run: doxygen ./Doxyfile
    - name: Archive documentation
      uses: actions/upload-artifact@v4
      with:
        name: doxygen-documentation
        path: doxygen/
